menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/2489238680
    GitHub: https://github.com/cnu4
    Rss: /atom.xml

favicon: /favicon.ico
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: fangxw-notes
cloudTie:

# Analytics
# google-analytics:
ga: UA-89489706-1

# Copyright Infomation
startyear: 2016
